# Generated by Django 3.2.8 on 2022-10-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userId', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
