# Generated by Django 3.2.8 on 2022-10-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_homeapp_user_friends_+', to='homeapp.User'),
        ),
    ]
