# Generated by Django 3.2.8 on 2022-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cateId',
            field=models.IntegerField(null=True),
        ),
    ]
