# Generated by Django 3.2.8 on 2022-10-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_category_cateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='channelName',
            field=models.CharField(max_length=60),
        ),
    ]
