# Generated by Django 3.2.8 on 2022-10-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_user_username'),
        ('dashboardapp', '0004_alter_subscription_channelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='channelId',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.subscription')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user')),
            ],
        ),
    ]
