# Generated by Django 3.2.8 on 2022-10-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0005_auto_20221008_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscription',
            old_name='chanelId',
            new_name='channelId',
        ),
    ]
