# Generated by Django 3.2.8 on 2022-10-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0006_rename_chanelid_user_subscription_channelid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.category')),
                ('channelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.subscription')),
            ],
        ),
    ]
