# Generated by Django 3.2.8 on 2022-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0007_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='channelImg',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
