# Generated by Django 3.2.8 on 2022-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0008_subscription_channelimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='channelImg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
